### PR TITLE
CTI Element Extractor dialog does not appear when posting with Referred URL（for issue #93）

### LINKED ISSUE #93: CTI Element Extractor dialog does not appear when posting with Referred URL
If you specify this URL in the Referred URL of S-TIP SNS, the post will be completed without displaying the CTI Element Extractor dialog.
<https://cycraft.com/download/%5BTLP-White%5D20200415%20Chimera_V4.1.pdf>

In the correct operation, the above PDF is downloaded from S-TIP, the contents are analyzed, IPv4 etc. are extracted and displayed in the dialog.

---  
S-TIP SNS の Referred URL にこのURLを指定すると、CTI Element Extractor のダイアログが表示されることなく、投稿が完了してしまう。
<https://cycraft.com/download/%5BTLP-White%5D20200415%20Chimera_V4.1.pdf>

正しい動作では、 S-TIP から 上記 PDF がダウンロードされ、中身を解析し、 IPv4 などをを抽出してダイアログに表示される。

### PR DESCRIPTION
**Pull request by uchimrina**

### CODE REVIEW

**Comment by stmtstk** [comment]
@uchimrina 

Please set a meaningful title.
It is possible to set the same title corresponding with the issue.

---

Pull Request のタイトルですが、対応 issue と同じタイトルでもいいので対応がわかる名前を付けてください。
後で修正一覧を見たときにわかりづらいと思いますので。
ご協力をお願いします。

**Review by ta-hiroki — APPROVED** [review]
I confirmed that there is no problem with the fix.

**Comment by stmtstk** [comment]
@ta-hiroki 
Thank you for your review and approval.

@uchimrina 
Thank you for your contribution and modify the title.

**Comment by uchimrina** [comment]
@stmtstk 
The title has been corrected.

**Pull request merged**
