### PR TITLE
fix to connect to slack and some file encoding issues

### PR DESCRIPTION
**Pull request by stmtstk**
Corespond to #17 .
 
I fixed to fail to connect to slack.
Python 2.7 uses slackclient library ver 1.x.
But Python 3.x uses slackclient library ver 2.x.

There are many gaps between ver1.x and 2.x.
https://github.com/slackapi/python-slackclient/wiki/Migrating-to-2.x

---

and I also fixed about file encoding issues.

---

And I found an encoding issues in RS repository.
We must merge RS and SNS at the same time.

I will open a pull request at RS repository soon.

### CODE REVIEW

**Comment by ykoji8681** [comment]
@stmtstk 
* It works well when I click "Save" button with Slack setting
* It causes "Internal Server Error" message when I click "Reboot Slack Thread" button.

Which is the correct operation?

**Comment by stmtstk** [comment]
@ykoji8681 
The first bullet is correct.
I will delete the "Reboot Slack" button and this function.

**Comment by stmtstk** [comment]
@ykoji8681  Sorry. I found an error.
I checked it. 
So please wait to merge this branch.

**Comment by stmtstk** [comment]
@ykoji8681 
OK, I fixed it.

I decided to leave a reboot slack thread button, because an S-TIP user may change Slack BOT Token.
If the Slack Bot Token is changed,  slack thread must be rebooted.
If an user changes just a Slack Bot Channel, it does not need to reboot the slack thread.

**Comment by ykoji8681** [comment]
Thanks, @stmtstk .

I will add following configuration to wiki.

* Modifying "OAuth Token" requires "Reboot Slack Thread"
* Only Modifying "Slack Bot Channel" doesn't require "Reboot Slack Thread"

**Pull request merged**
