### PR TITLE
Change the sentence from "More Feeds" to "Last post. Check new posts." Issue#67

### PR DESCRIPTION
**Pull request by tkhsknsk**

### CODE REVIEW

**Comment by stmtstk** [comment]
@rmasuoka Could you review if this sentence is appropriate or not?

**Review by stmtstk — CHANGES_REQUESTED** [review]
Could you modify the sentences?

"More Feeds" -> "End of Feed"
"Check New Posts" -> "Reload"

**Comment by stmtstk** [comment]
@tkhsknsk 
Kindly notification of the request changes.

**Comment by tkhsknsk** [comment]
@stmtstk 
All right.
I will revise it to the requested sentence.

**Comment by tkhsknsk** [comment]
@stmtstk 
Is the following format OK?

Non-Japanese
End of Feed. [Reload](http://example.com)
(URL is dummy)

Japanese
フィードの最後 - [再取得](http://example.com)
(URL is dummy)

**Comment by stmtstk** [comment]
@tkhsknsk 

OK.

**Review by stmtstk — APPROVED** [review]

**Comment by stmtstk** [comment]
Thanks for your contribution.

**Pull request merged**
